language: node_js
node_js: stable
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
  - secure: JFx8+UndSLcj0YzDRUp8rwpDgAJubVVk2uZeLyo9Cw36Ug9Vks8Vp5VVBIhiAMAWOoFobZAu5KEaHK5r1A9CjlfA7eQz2AUDNV4xPPQcWZFXPqdbmjNEaXrmxzlx8aV6Lvawjm/uYbSXA+D4k22I10Y3D594kDFh+MNA/aaE2qpueeCAvfSdYrdyJZXQ46HOvhxT6pS5L4IYbAB1722wZWZLvCioWEe34U9fRiWxq0t05ylv6anUjUX48Hg2QsuQVZK8tlV8konLLG/jdCw2p5tx9+PEr0aREHeka335Fi2ABPwFQk73q5eBtfC0CtzsNABU+7UPW8i+PqS12gxUBy9tJ1lP41/02zc4vnY7D17jiihutIOots1Z7bEqU7it0bSAtJTwTL46y9XEstT9jtG4BXii5hWrJKf/rgJJ4VOdgOgKe0piSDz1HFzTkJj7e7yRf2CpDe0m8ZK04+ytMuzfkQ8zKG7fe1hsS/pNHMK+6HFFnOB7nw7x7XaqoNFcNtlJrSdTthcCqPYehUKzIFcZtMGkPJoqSxI/Na+GoxlNN8hZe2XhubDRmubkkdFLEJn/b+9XvSz44yI3UhkHlM1nTwHNnGsf3xQST3otmtdjGZMT0VGNIbnZiLo8FHJqiTYcwqjT+H/v+hbMa6vPGNDZYTJQFuH0uzRwHVj2/u0=
  - secure: 2HiOznfMDGZySVhfjLPYvhW+XDLlyueWTZEeUthIKw4iCxsP4N+8fN2bOQ5MgG14Pr705BV31bbxknRgswZ+3NHp+cc78Adp8A28UNFf4OoptzcuuR2IZVC31GGlu0nE2nfWZRlmjPKsuw4Ap0DZrH/GXAdTaDHT4Yb/hEhb4tDMwGSNNTTDBycVD8Vb6RcnS4C0oPmEjqtk0iVbI9tn9l3tILMmq0A2wNPLYdgdF2VGrPHv6ggr8u1dP82b4mjcy5aNX2nSXCYMBhZxFmR70RA4Fy20bySrreFvM5rbxnUQ3maYhs7vaetwotrC7Sabe8LEroG4XmkIMKTN/XRx7B1EflwEiGiNDrJ7cdYers9F0eyl7guCeBuJNaXCYnTkG37U34kQorJErJy7yR3No99d7Yi9bn4SVr2peYcCSJ4eOWxjDlB4ZZwFhc9LW3ptPcHcW2JBaWjSZL52bTPm1tn3MoWtEUjHXoEo/c+D80qCaX2gGbvN75lE6P3J1i7kEax7/TqKVLBADg4TpT3ZevVo5Ub1hTbR3ROjP6v9rf5yqzHg8XHE3j1rU/u2ISTqGoPTTP6Dp75KECpVIbBlwZL0prL7KSFv/NjlNG63BIR90MM0Q/Is8GqJG5bZMI5GevdmnTQXl5VUWn+AuIGrJAlK+ndWyWBkwk2x4pgkMb0=
